apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: git-state-dev
servers: 1
agents: 0
image: rancher/k3s:v1.37.1-k3s1
kubeAPI:
  hostIP: 127.0.0.1
ports:
  - port: 127.0.0.1:3000:30080
    nodeFilters: [server:0]
  - port: 127.0.0.1:8080:30443
    nodeFilters: [server:0]
options:
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  k3d:
    wait: true
    timeout: 180s
