---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gitops.example.io
  resources:
  - clustergitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.example.io
  resources:
  - clustergitconfigs/status
  - gitresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gitops.example.io
  resources:
  - gitresources
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.example.io
  resources:
  - gitresources/finalizers
  verbs:
  - update
- apiGroups:
  - testing.gitops.example.io
  resources:
  - statusobjects
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: argocd
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resourceNames:
  - git-resources
  resources:
  - applicationsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: git-state-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
