resources:
- ../default
patches:
- target:
    kind: Deployment
    name: controller-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --allow-http=true
